module.exports = {
  prefixName: 'help',
  async execute(message, args, client){
    const embed = {
      color: 0x5865F2,
      title: '🎮 GAMERZ WORKSHOP — Help',
      description: [
        '**🔨 Moderation**',
        '`/ban` — Ban a member',
        '`/kick` — Kick a member',
        '`/mute` — Timeout a member (e.g. 10m, 1h, 28d)',
        '`/unmute` — Remove timeout',
        '`/warning rule` — Warn by rule (r1–r5)',
        '`/warning custom` — Warn with custom reason',
        '`/warning status` — View member warnings',
        '`/clearwarn` — Clear one or all warnings',
        '`/purge` — Bulk delete 1–100 messages',
        '`/unban` — Unban user by ID',
        '`/slowmode` — Set channel slowmode',
        '`/lock` — Lock a channel',
        '`/unlock` — Unlock a channel',
        '`/lockdown start` — Lock ALL channels',
        '`/lockdown end` — Unlock ALL channels',
        '`/role add/remove` — Add or remove a role',
        '',
        '**🛡️ Security**',
        '`/setup logs` — Set a log channel',
        '`/setup view` — View log channel settings',
        '`/security status` — View all security settings',
        '`/security toggle` — Toggle a security feature',
        '`/security joinrole` — Set auto-join role',
        '`/security trappedchannel` — Set honeypot channel',
        '`/security joinmsg` — Set new member DM message',
        '`/antiraid on/off` — Toggle anti-raid',
        '`/antiraid unlock` — Unlock channels after raid',
        '`/modconfig addmod/removemod` — Manage mod roles',
        '`/modconfig addadmin/removeadmin` — Manage admin roles',
        '`/modconfig view` — View mod/admin roles',
        '',
        '**ℹ️ Info**',
        '`/help` — This command list',
        '`/userinfo` — User details',
        '`/serverinfo` — Server stats',
        '`/botinfo` — Bot stats',
        '`/avatar` — View user avatar',
        '',
        '**🔧 Utility**',
        '`/ping` — Bot latency',
        '`/uptime` — Bot uptime',
        '`/suggest` — Submit a suggestion',
        '`/poll` — Create a poll (2–4 options)',
        '`/say` — Make bot send a message',
        '`/embed` — Send a custom embed',
        '`/nick` — Change member nickname',
        '`/banlist` — View banned users',
        '`/activity` — Set bot activity & status (Playing, Watching, Listening, Streaming, Custom)',
        '',
        '**⌨️ Prefix Commands**',
        '`!help` — This help message',
        '`!ping` — Bot latency',
        '`!uptime` — Bot uptime',
      ].join('\n'),
      footer: { text: '🎮 GAMERZ WORKSHOP | Use /slash commands for full functionality' },
      timestamp: new Date().toISOString(),
    };
    await message.reply({ embeds: [embed] });
  },
};
